apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - name: TraceID
          datasourceUid: jaeger
          matcherRegex: '"trace_id"\s*:\s*"([a-fA-F0-9]+)"'
          url: '$${__value.raw}'
          urlDisplayLabel: View trace

  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{compose_service=~".+"} | json | trace_id=`$${__span.traceId}`'
      nodeGraph:
        enabled: true
